baseURL: 'open.ecoacoustics.info'
enableGitInfo: true
languageCode: 'en-us'
title: Open Ecoacoustics
theme: hugo-book-custom
markup:
    goldmark:
        parser:
            attribute:
                block: true
                title: true
        renderer:
            unsafe: true
params:
    BookSection: resources
    Organization: 'Open Ecoacoustics'
    ThemeColor: '#CB7E30'
    # The format of the following is very precise.
    # No punctuation, spaces needed, commas needed.
    ThemeColorHsl: 30deg, 62%, 49% # '#CB7E30'
    ThemeShades:
        # https://codepen.io/claviska/pen/QWveRgL
        '50': 252 249 245
        '100': 247 234 222
        '200': 240 219 196
        '300': 233 201 168
        '400': 224 177 130
        '500': 211 146 80
        '600': 186 115 44
        '700': 153 95 36
        '800': 126 78 30
        '900': 90 56 21
        '950': 55 34 13
    FavIcon: 'oe-icon.svg'
    Logo: 'oe-logo-horizontal.svg'
sectionPagesMenu: "main"
