[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.134.3"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

# needed to embed stackblitz as an iframe because they rely on SharedArrayBuffer
[[headers]]
  for = "/posts/web-components"
    [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
