[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.134.3"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "hugo --minify --buildDrafts --buildFuture"

[[headers]]
  for = "/book.min.*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.search.min.*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*_hu*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/home/*_hu*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
